# This is a docker-compose file for a Kafka cluster with a single node.
# It is used to test the Kafka client library.

services:
  kafka:
    image: confluentinc/cp-kafka:7.7.5
    container_name: kafka
    ports:
      - "9092:9092" # External access port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # --- Listener Configuration ---
      # Define listener names (security protocol mapping)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # Address to listen for (0.0.0.0 allows all IP addresses)
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Address to advertise to clients (advertised address)
      # INTERNAL: Docker internal service (Control Center) uses 'kafka' host name
      # EXTERNAL: External (Host) uses IPv4 loopback by default to avoid Windows preferring IPv6 (::1) for "localhost"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      # Listener for inter-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # --------------------------------

      CLUSTER_ID: BF9kORqkTlODNgqnk3CEGA
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # Single node setup (limit replication factor to 1)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_MESSAGE_MAX_BYTES: 52428800
      KAFKA_REPLICA_FETCH_MAX_BYTES: 52428800

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka_data:/var/lib/kafka/data

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.5
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      # Connect to Kafka's internal listener port (29092)
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:29092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: ""
      CONTROL_CENTER_KSQL_ENABLE: "false"
      # Enable UI monitoring functionality (for development)
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      PORT: 9021

volumes:
  kafka_data:
